version: "3"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  statsd:
    image: prom/statsd-exporter:v0.18.0
    entrypoint: /bin/statsd_exporter
    command:
      - "--statsd.mapping-config=/etc/statsd-exporter/conf.yaml"
    expose:
      - 9125
      - 9102
    ports:
      - 9125:9125
      - 9102:9102
    networks:
      - ratelimit-network
    volumes:
      - ./examples/prom-statsd-exporter/conf.yaml:/etc/statsd-exporter/conf.yaml

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 8088:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
      - statsd
    networks:
      - ratelimit-network
    volumes:
      - ./examples/ratelimit/config:/data/ratelimit/config
    environment:
      - USE_STATSD=true
      - STATSD_HOST=statsd
      - STATSD_PORT=9125
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false
      - CONFIG_TYPE=${CONFIG_TYPE:-FILE}
      - CONFIG_GRPC_XDS_NODE_ID=test-node-id
      - CONFIG_GRPC_XDS_SERVER_URL=ratelimit-xds-config-server:18000

  ratelimit-xds-config-server:
    image: ratelimit-xds-config-server:latest
    build:
      context: examples/xds-sotw-config-server
      dockerfile: Dockerfile
    command: ["-nodeID", "test-node-id", "-port", "18000", "-debug", "true"]
    expose:
      - 18000
    networks:
      - ratelimit-network
    profiles:
      - xds-config

  envoy-proxy:
    image: envoyproxy/envoy-dev:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./examples/envoy/proxy.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
      - "8888"
      - "8001"
    ports:
      - "8888:8888"
      - "8001:8001"

  envoy-mock:
    image: envoyproxy/envoy-dev:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node mock"
      - "--service-cluster mock"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./examples/envoy/mock.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
      - "9999"
    ports:
      - "9999:9999"

  # TeaStore services start here
  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
    ports:
      - "8083:8080"
    networks:
      - ratelimit-network

  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - ratelimit-network

  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    ports:
      - "8084:8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/persistence:/kieker/logs/
    networks:
      - ratelimit-network

  auth:
    image: thiva-auth:latest
    expose:
      - "8080"
    ports:
      - "8085:8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/auth:/kieker/logs/
    networks:
      - ratelimit-network

  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    ports:
      - "8086:8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/image:/kieker/logs/
    networks:
      - ratelimit-network

  recommender:
    image: thiva-recommender:latest
    expose:
      - "8080"
    ports:
      - "8087:8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/recommender:/kieker/logs/
    networks:
      - ratelimit-network

  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/webui:/kieker/logs/
    networks:
      - ratelimit-network

networks:
  ratelimit-network: